spring:
  application:
    name: authentication
  datasource:
    url: jdbc:postgresql://localhost:5433/authenticationdb
    username: postgres
    password: password
  cloud:
    vault:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5433/authenticationdb
    user: flyway
    password: password

server:
  port:
    8081