spring:
  application:
    name: user
  datasource:
#    todo set up vault for these credentials
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/userdb
    user: flyway
    password: password