spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
  cloud:
    vault:
      uri: http://localhost:8200
      token: myroot
      database:
        enabled: true
        role: userdb
        backend: database
        username-property: spring.datasource.username
        password-property: spring.datasource.password
      kv:
        enabled: true
        application-name: user
        backend: secret
  config:
    import: vault://
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/userdb
    user: postgres
    password: password