name: vault

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault_server
    ports:
      - "8200:8200"
    env_file:
      - .env
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
    command: server -dev

volumes:
  vault_data: