# https://hub.docker.com/_/postgres
name: user

services:
  db:
    image: postgres:latest
    container_name: user_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - vault_net

volumes:
  db_data:

networks:
  vault_net:
    external: true