name: user

services:
  db:
    image: postgres:latest
    container_name: user_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

volumes:
  user_db_data: